import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google"; 
import Navbar from "./components/NavComponent/NavComponent";
import Sidenavbar from "./components/SideNavbar/SideNavbar";


const poppins = Poppins({
  weight: ["400", "600", "700"], 
  subsets: ["latin"],
  variable: "--font-poppins", 
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body className={`${poppins.variable} antialiased`}>
      <div className="flex flex-col min-h-screen">
      
        <Navbar />

    
        <div className="flex flex-1">
          
          <Sidenavbar  />

          
          <main className="flex-1 p-4">{children}</main>
        </div>
      </div>
    </body>
  </html>
  );
}
